// AUTO-GENERATED by scripts/generate-enums-from-constants.ts. Do not edit.
export const ENUM_OPTIONS: Record<string, readonly string[]> = {
  "action_step_status": [
    "Complete",
    "Incomplete"
  ],
  "active_inactive": [
    "Active",
    "Inactive",
    "Removed"
  ],
  "admissions_system_options": [
    "TC",
    "School Cues"
  ],
  "advice_panel_stages": [
    "Visioning",
    "Planning"
  ],
  "age_spans": [
    "0-3",
    "3-6",
    "6-9",
    "9-12",
    "12-15",
    "15-18"
  ],
  "age_spans_rev": [
    "0-1",
    "1-3",
    "3-6",
    "6-9",
    "9-12",
    "12-15",
    "15-18"
  ],
  "ages-grades": [
    "Infants",
    "Toddlers",
    "PK3",
    "PK4",
    "K",
    "1st",
    "2nd",
    "3rd",
    "4th",
    "5th",
    "6th",
    "7th",
    "8th",
    "9th",
    "10th",
    "11th",
    "12th"
  ],
  "authorizor_decisions": [
    "Approved",
    "Approved, with contingency",
    "Deferred decision",
    "Denied"
  ],
  "automation_step_trigger": [
    "Request prelim advice for $3k+",
    "Request full advice",
    "Waiting for prelim advice",
    "Waiting for full advice",
    "Proceed",
    "Processing",
    "Waiting for prereqs",
    "Complete"
  ],
  "budget_utility_options": [
    "WF v4"
  ],
  "business_insurance_options": [
    "Alliant",
    "other (in process w/ Alliant)",
    "other"
  ],
  "certification_completion_status": [
    "Certified",
    "Training"
  ],
  "charter_app_status": [
    "Pre application",
    "Preparing application",
    "Awaiting decision",
    "Authorized, preparing to open"
  ],
  "charter_status": [
    "Awaiting start of cohort",
    "Open",
    "Paused",
    "Applying",
    "Approved - Year 0",
    "Application Submitted - Waiting"
  ],
  "cohort_type": [
    "Charter",
    "Blooms"
  ],
  "dev_note_type": [
    "crash",
    "unexpected search results",
    "unexpected behavior",
    "UI refinement",
    "new functionality request",
    "other"
  ],
  "developmental_planes": [
    "Infants",
    "Toddlers",
    "Primary",
    "Lower Elementary",
    "Upper Elementary",
    "Adolescent / JH",
    "High School"
  ],
  "discovery_statuses": [
    "Complete",
    "In process",
    "Paused"
  ],
  "domain_name_options": [
    "internal",
    "external"
  ],
  "educ_attainment_options": [
    "Did not graduate high school",
    "Graduated high school or GED",
    "Some college or two-year degree",
    "Graduated college (four-year degree)",
    "Some graduate school",
    "Completed graduate school"
  ],
  "email_address_categories": [
    "personal",
    "work - non-wildflower",
    "work - wildflower school",
    "work - wildflower foundation",
    "school"
  ],
  "exemption_statuses": [
    "Exempt",
    "Non-exempt"
  ],
  "fee_change_types": [
    "Change in exemption status",
    "Change in fee",
    "Change likelihood of payment"
  ],
  "fiscal_year_end": [
    "06/30",
    "12/31"
  ],
  "gender_categories": [
    "Female",
    "Male",
    "Gender Non-Conforming",
    "Other"
  ],
  "google_voice_options": [
    "internal license",
    "external license"
  ],
  "governance_models": [
    "Independent",
    "Charter",
    "Community Partnership",
    "District",
    "Exploring Charter",
    "NULL"
  ],
  "group_exemption_status": [
    "Active",
    "Never part of group exemption",
    "Withdrawn",
    "Applying",
    "Issues"
  ],
  "gsuite_roles_options": [
    "School Admin - School Orgs"
  ],
  "guide_types": [
    "Ops Guide",
    "Entrepreneur",
    "Equity Coach",
    "Open Schools Support"
  ],
  "gusto_options": [
    "yes (under WF)",
    "yes (independent)",
    "yes",
    "no- local system",
    "no"
  ],
  "high_med_low": [
    "Low",
    "Medium",
    "High"
  ],
  "income_categories": [
    "Very low",
    "Low",
    "Middle",
    "Upper",
    "Prefer not to respond"
  ],
  "kanban_visibility": [
    "expanded",
    "collapsed",
    "suppressed"
  ],
  "languages": [
    "English",
    "Spanish - Espa├▒ol",
    "Mandarin - Σ╕¡µûç",
    "Hindi - αñ╣αñ┐αñ¿αÑìαñªαÑÇ",
    "French - Fran├ºais",
    "Japanese - µùÑµ£¼Φ¬₧",
    "Arabic - ╪º┘ä╪╣┘Ä╪▒┘Ä╪¿┘É┘è┘Ä┘æ╪⌐",
    "Urdu - ╪º┘Å╪▒╪»┘Å┘ê",
    "Hungarian - Hungarian",
    "Haitian Creole - Kreyol Ayisyen",
    "Gujarati - α¬ùα½üα¬£α¬░α¬╛α¬ñα½Ç",
    "Fujian- Fujian",
    "Russian - ╤Ç╤â╤ü╤ü╨║╨╕╨╣ ╤Å╨╖╤ï╨║",
    "Korean - φò£Ω╡¡∞û┤",
    "Cantonese - Gw├│ngd┼½ng w├í",
    "Tai-Kadai - α╣äα╕ùα╕ó / α║₧α║▓α║¬α║▓α║Ñα║▓α║º",
    "Portuguese - Portugu├¬s",
    "Tami - α«ñα««α«┐α«┤α»ì",
    "Burmese - ßÇÖßÇ╝ßÇößÇ║ßÇÖßÇ¼ßÇàßÇ¼",
    "Yoruba",
    "Other"
  ],
  "legal_structure_options": [
    "Independent organization",
    "Part of another organization",
    "Part of a charter",
    "Multiple WF schools in a single entity"
  ],
  "loan_status_options": [
    "Interest Only Period",
    "Paid Off",
    "Principal Repayment Period"
  ],
  "loan_vehicle_options": [
    "LF II",
    "Sep",
    "Spring Point",
    "TWF",
    "TWF->LF II"
  ],
  "location_types": [
    "Mailing address - no physical school",
    "Physical address - does not receive mail",
    "School address and mailing address"
  ],
  "logo_designer_options": [
    "internal design",
    "external design"
  ],
  "membership_action_options": [
    "Signed Membership Agreement",
    "Withdrew from Network",
    "Sent Termination Letter"
  ],
  "montessori_associations": [
    "AMI",
    "AMS",
    "IMC",
    "MEPI",
    "PAMS",
    "Independent",
    "Other"
  ],
  "nonprofit_paths": [
    "Group exemption",
    "Direct",
    "Charter",
    "Partner"
  ],
  "nps": [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10"
  ],
  "on_national_website_options": [
    "added",
    "removed",
    "ready to add"
  ],
  "partner_roles": [
    "TL",
    "Affiliate of Charter Partner",
    "Ops Guide",
    "Teacher Leader",
    "Foundation Partner",
    "Regional Entrepreneur",
    "School Supports Partner",
    "Finance Administrator"
  ],
  "pre_wf_employment_statuses": [
    "1"
  ],
  "pronouns": [
    "he/him/his",
    "she/her/hers",
    "they/them/theirs",
    "other"
  ],
  "qbo_options": [
    "internal license - active",
    "external license",
    "Not WF - Unknown software"
  ],
  "race_ethnicity_categories": [
    "african_american",
    "asian_american",
    "hispanic",
    "middle_eastern",
    "native_american",
    "pacific_islander",
    "white",
    "other"
  ],
  "school_calendar_options": [
    "9-month",
    "10-month",
    "Year-round"
  ],
  "school_roles": [
    "Teacher Leader",
    "Emerging Teacher Leader",
    "Founder",
    "Classroom Staff",
    "Fellow",
    "Other"
  ],
  "school_schedule_options": [
    "Before Care",
    "Morning Care",
    "Afternoon Care",
    "After Care"
  ],
  "school_statuses": [
    "Emerging",
    "Open",
    "Paused",
    "Disaffiliated",
    "Permanently Closed",
    "Placeholder"
  ],
  "ssj_board_dev_status": [
    "No board",
    "Board is forming, 1-2 mtgs",
    "Board is developed and engaged, 3+ mtgs"
  ],
  "ssj_budget_ready_for_next_steps_enum": [
    "No",
    "Unsure",
    "Yes"
  ],
  "ssj_building4good_status_enum": [
    "Matched",
    "Requested",
    "Upcoming"
  ],
  "ssj_cohort_status_enum": [
    "Left Cohort",
    "Returning for Later Cohort",
    "Switched Ops Guide Supports",
    "Transitioned to Charter Application Supports"
  ],
  "ssj_date_shared_with_n4g_enum": [
    "2020-01-15"
  ],
  "ssj_facility_enum": [
    "Purchased building",
    "Searching, intending to buy",
    "Searching, intending to rent",
    "Identified prospect(s)",
    "Signed lease",
    "Unsure"
  ],
  "ssj_form_type": [
    "Get Involved",
    "Start a School"
  ],
  "ssj_has_partner_enum": [
    "No partner",
    "Partnership established",
    "Partnership In development"
  ],
  "ssj_on_track_for_enrollment_enum": [
    "Maybe (process is ready, no prospective students)",
    "No (process unclear/unpublished, limited/no family engagement)",
    "Yes - tuition published, plan and community engagement underway"
  ],
  "ssj_ops_guide_support_track_enum": [
    "Cohort",
    "1:1 support"
  ],
  "ssj_pathway_to_funding_enum": [
    "Maybe, prospects identified but not secured",
    "No, startup funding unlikely",
    "Yes, full funding likely"
  ],
  "ssj_seeking_wf_funding_enum": [
    "No",
    "Yes, grant",
    "Yes, grant; Yes, loan",
    "Yes, loan",
    "Yes, loan; Yes, grant"
  ],
  "ssj_stages": [
    "Visioning",
    "Planning",
    "Startup",
    "Year 1",
    "Complete"
  ],
  "ssj_tool_enum": [
    "Charter Slides",
    "Google Slides",
    "My Wildflower - Sensible Default",
    "Platform Pilot"
  ],
  "state_abbreviation_enum": [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "DC",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
    "PR"
  ],
  "tc_admissions_options": [
    "v1",
    "yes"
  ],
  "tc_recordkeeping_options": [
    "yes (under WF)"
  ],
  "training_types": [
    "Lead Guide",
    "Assistant",
    "Administrator"
  ],
  "transparent_classroom_options": [
    "Internal license",
    "Internal License - removed",
    "External license",
    "Other record keeping system"
  ],
  "use_of_proceeds_options": [
    "Combine 2 loans",
    "Expansion",
    "Move",
    "Operations",
    "Renovations / Construction",
    "Security deposit",
    "Start-up"
  ],
  "website_tool_options": [
    "external platform",
    "wordpress v1",
    "wordpress v2",
    "wordpress original",
    "Wix v1",
    "Wix v2"
  ]
};
export const FIELD_ENUMS: Record<string, string> = {
  "public.action_steps.item_status": "action_step_status",
  "public.Insert.stage": "advice_panel_stages",
  "public.Insert.app_status": "charter_app_status",
  "public.Insert.auth_decision": "authorizor_decisions",
  "public.Insert.beg_age": "ages-grades",
  "public.Insert.end_age": "ages-grades",
  "public.Insert.current_fy_end": "fiscal_year_end",
  "public.Insert.group_exemption_status": "group_exemption_status",
  "public.Insert.initial_target_planes": "developmental_planes",
  "public.Insert.status": "school_statuses",
  "public.Insert.notes_type": "dev_note_type",
  "public.Insert.user_priority": "high_med_low",
  "public.Insert.category": "email_address_categories",
  "public.Insert.automation_step_trigger": "automation_step_trigger",
  "public.Insert.group_exemption_status_after_action": "group_exemption_status",
  "public.Insert.type": "guide_types",
  "public.Insert.partner_roles": "partner_roles",
  "public.Insert.language_array": "languages",
  "public.Insert.states_array": "state_abbreviation_enum",
  "public.Insert.loan_status": "loan_status_options",
  "public.Insert.use_of_proceeds": "use_of_proceeds_options",
  "public.Insert.vehicle": "loan_vehicle_options",
  "public.Insert.action": "membership_action_options",
  "public.Insert.association": "montessori_associations",
  "public.Insert.cert_completion_status": "certification_completion_status",
  "public.Insert.cert_level": "age_spans_rev",
  "public.Insert.childhood_income": "income_categories",
  "public.Insert.educ_attainment": "educ_attainment_options",
  "public.Insert.gender": "gender_categories",
  "public.Insert.hh_income": "income_categories",
  "public.Insert.montessori_certs": "age_spans_rev",
  "public.Insert.other_languages": "languages",
  "public.Insert.primary_languages": "languages",
  "public.Insert.pronouns": "pronouns",
  "public.Insert.race_ethnicity": "race_ethnicity_categories",
  "public.Insert.discovery_status": "discovery_statuses",
  "public.Insert.gsuite_roles": "gsuite_roles_options",
  "public.Insert.in_tl_google_grp": "active_inactive",
  "public.Insert.in_wf_directory": "active_inactive",
  "public.Insert.on_natl_website": "active_inactive",
  "public.Insert.on_slack": "active_inactive",
  "public.Insert.logo_designer": "logo_designer_options",
  "public.Insert.ssj_board_development": "ssj_board_dev_status",
  "public.Insert.ssj_budget_ready_for_next_steps": "ssj_budget_ready_for_next_steps_enum",
  "public.Insert.ssj_building4good_status": "ssj_building4good_status_enum",
  "public.Insert.ssj_facility": "ssj_facility_enum",
  "public.Insert.ssj_has_partner": "ssj_has_partner_enum",
  "public.Insert.ssj_on_track_for_enrollment": "ssj_on_track_for_enrollment_enum",
  "public.Insert.ssj_ops_guide_support_track": "ssj_ops_guide_support_track_enum",
  "public.Insert.ssj_pathway_to_funding": "ssj_pathway_to_funding_enum",
  "public.Insert.ssj_readiness_to_open_rating": "high_med_low",
  "public.Insert.ssj_seeking_wf_funding": "ssj_seeking_wf_funding_enum",
  "public.Insert.ssj_stage": "ssj_stages",
  "public.Insert.ssj_target_state": "state_abbreviation_enum",
  "public.Insert.ssj_tool": "ssj_tool_enum",
  "public.Insert.admissions_system": "admissions_system_options",
  "public.Insert.ages_served": "age_spans_rev",
  "public.Insert.budget_utility": "budget_utility_options",
  "public.Insert.business_insurance": "business_insurance_options",
  "public.Insert.domain_name": "domain_name_options",
  "public.Insert.google_voice": "google_voice_options",
  "public.Insert.governance_model": "governance_models",
  "public.Insert.gusto": "gusto_options",
  "public.Insert.legal_structure": "legal_structure_options",
  "public.Insert.nonprofit_path": "nonprofit_paths",
  "public.Insert.on_national_website": "on_national_website_options",
  "public.Insert.qbo": "qbo_options",
  "public.Insert.school_calendar": "school_calendar_options",
  "public.Insert.school_sched": "school_schedule_options",
  "public.Insert.tc_admissions": "tc_admissions_options",
  "public.Insert.tc_recordkeeping": "tc_recordkeeping_options",
  "public.Insert.transparent_classroom": "transparent_classroom_options",
  "public.Insert.website_tool": "website_tool_options",
  "public.Insert.form_type": "ssj_form_type"
};
