services:
  - type: web
    name: wildflower-server
    env: node
    rootDir: server
    plan: standard
    buildCommand: |
      corepack enable && corepack prepare pnpm@10.14.0 --activate \
      && pnpm install --no-frozen-lockfile \
      && pnpm run build
    startCommand: pnpm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      # REQUIRED: Airtable credentials for core datasets
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      # OPTIONAL: Postgres for loan system (skip if not used)
      # - key: DATABASE_URL
      #   sync: false
      # OPTIONAL: Allow specific frontend origins (comma-separated). Example: https://wftls.vercel.app
      # - key: CORS_ORIGIN
      #   value: "https://your-frontend.example.com"
      # Add your required server env vars here or in Render dashboard
      # - key: SUPABASE_URL
      #   sync: false
      # - key: SUPABASE_SERVICE_ROLE_KEY
      #   sync: false
