// Auto-generated from schema.txt. Do not edit manually.
// Base: School dbase (appJBT9a4f3b7hWQ2)

export const AIRTABLE_TABLES = {
  SCHOOLS: "Schools",
  CHARTERS: "Charters",
  LOCATIONS: "Locations",
  EDUCATORS: "Educators",
  EDUCATORS_X_SCHOOLS: "Educators x Schools",
  GRANTS: "Grants",
  GRANTS_ADVICE_LOG: "Grants Advice Log",
  LOANS: "Loans",
  GOVERNANCE_DOCS: "Governance docs",
  _990S: "990s",
  LOAN_PAYMENTS: "Loan payments",
  EVENTS: "Events",
  EVENT_ATTENDANCE: "Event attendance",
  MAILING_LISTS: "Mailing lists",
  MONTESSORI_CERTS: "Montessori Certs",
  SSJ_TYPEFORMS__START_A_SCHOOL: "SSJ Typeforms: Start a School",
  SSJ_FILLOUT_FORMS: "SSJ Fillout Forms",
  GUIDES: "Guides",
  GUIDES_ASSIGNMENTS: "Guides Assignments",
  SCHOOL_NOTES: "School notes",
  EDUCATOR_NOTES: "Educator notes",
//  FAMILY_SURVEY_NON_TC_DATA_2021_22: "Family survey non-TC data 2021-22",
//  FAMILY_SURVEY___SCHOOL_INPUTS: "Family survey - school inputs",
//  FAMILY_SURVEY___HUB_INPUTS: "Family survey - hub inputs",
//  FAMILY_SURVEY___EXCLUDED_CLASSROOM_INPUTS: "Family survey - excluded classroom inputs",
//  FAMILY_SURVEY___EXCLUDED_STUDENT_INPUTS: "Family survey - excluded student inputs",
//  FAMILY_SURVEY___FIELD_NAME_INPUTS: "Family survey - field name inputs",
//  ETHNICITY_CATEGORIES: "Ethnicity categories",
//  ETHNICITY_MAPPING: "Ethnicity mapping",
//  GENDER_CATEGORIES: "Gender categories",
//  GENDER_MAPPING: "Gender mapping",
//  HOUSEHOLD_INCOME_CATEGORIES: "Household income categories",
//  HOUSEHOLD_INCOME_MAPPING: "Household income mapping",
//  NPS_CATEGORIES: "NPS categories",
//  BOOLEAN_CATEGORIES: "Boolean categories",
//  BOOLEAN_MAPPING: "Boolean mapping",
//  FIELD_CATEGORIES: "Field Categories",
//  FIELD_MAPPING: "Field Mapping",
//  FAMILY_SURVEY: "Family Survey",
//  EDUCATOR_GIFTS: "Educator Gifts",
//  SCHOOL_GIFTS: "School Gifts",
  TRAINING_GRANTS: "Training Grants",
//  MARKETING_ASSETS: "Marketing assets",
//  PLATFORM_EDUCATORS___PARTNERS: "Platform Educators & Partners",
//  PLATFORM_SCHOOL: "Platform School",
//  PLATFORM_EDUCATORS_X_SCHOOLS: "Platform Educators x Schools",
  PUBLIC_FUNDING: "Public funding",
  ACTION_STEPS: "Action steps",
//  MEMBERSHIP_FEE_CHANGE_LOG: "Membership fee change log",
//  MEMBERSHIP_FEE_BILLING_SCHEDULES: "Membership fee billing schedules",
//  MEMBERSHIP_FEE_CREDITS: "Membership fee credits",
//  MEMBERSHIP_FEE_INVOICES: "Membership fee invoices",
//  MEMBERSHIP_FEE___GENERATE_INVOICES: "Membership fee - generate invoices",
  EVENT_TYPES: "Event types",
  QBO_SCHOOL_CODES: "QBO School Codes",
//  EMAILS: "Emails",
  MONTESSORI_CERT_LEVELS: "Montessori Cert Levels",
  MONTESSORI_CERTIFIERS: "Montessori Certifiers",
  MONTESSORI_CERTIFIERS___OLD_LIST: "Montessori Certifiers - old list",
  RACE_AND_ETHNICITY: "Race and Ethnicity",
  BOARD_SERVICE: "Board Service",
//  EMAIL_SYNC_ERRORS: "Email Sync Errors",
  LEAD_ROUTING_AND_TEMPLATES: "Lead Routing and Templates",
  STATES_ALIASES: "States Aliases",
//  MEETINGS: "Meetings",
  MEMBERSHIP_TERMINATION_STEPS: "Membership termination steps",
  MEMBERSHIP_TERMINATION_STEPS_AND_DATES: "Membership termination steps and dates",
  COHORTS: "Cohorts",
//  ADVICE_PROCESS: "Advice Process",
//  AUTOMATIONS: "Automations",
//  REUSABLE_CODE: "Reusable Code",
//  OVERALL_REUSABLE_CODE: "Overall Reusable Code",
//  KEY_VALUE_PAIRS: "Key Value Pairs",
//  ROADMAP: "Roadmap",
//  METADATA: "Metadata",
//  SCHOOL_YEAR: "School year",
//  MEMBERSHIP_FEE_SCHOOL_X_YEAR: "Membership fee school x year",
//  MEMBERSHIP_FEE_UPDATES: "Membership fee updates",
  MARKETING_SOURCES_MAPPING: "Marketing sources mapping",
  MARKETING_SOURCE_OPTIONS: "Marketing source options",
  ANNUAL_ENROLLMENT_AND_DEMOGRAPHICS: "Annual enrollment and demographics",
  CHARTER_ROLES: "Charter roles",
  CHARTER_AUTHORIZERS_AND_CONTACTS: "Charter authorizers and contacts",
  REPORTS_AND_SUBMISSIONS: "Reports and submissions",
  ASSESSMENTS: "Assessments",
  ASSESSMENT_DATA: "Assessment data",
  CHARTER_APPLICATIONS: "Charter applications",
  AGES_GRADES: "Ages-Grades",
  SUPABASE_JOIN_990_WITH_SCHOOL: "Supabase join 990 with school",
  EMAIL_ADDRESSES: "Email Addresses",
  PARTNERS_COPY: "Partners copy",
} as const;
